using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Treatment_Mapper.Mapping_Functions
{
    public class CodeValidation

        
    {
        public Dictionary<string, string> eng_Codes { get { return eng_valid_codes; } }
        public Dictionary<string, string> sco_Codes { get { return sco_valid_codes; } }

        public readonly Dictionary<string,string> eng_valid_codes = new Dictionary<string, string>()
        {
            {"100","Exam"},
            {"101","Exam & Scale & Polish"},
            {"102","New Patient Exam"},
            {"103","Review"},
            {"104","Assessment & Advice"},
            {"105","Small Radiograph"},
            {"106","Intraoral Photographs"},
            {"107","Panoral Radiograph"},
            {"108","Cephalometric Radiographic Image"},
            {"109","Clinical Photographs"},
            {"110","Periapical X Ray"},
            {"111","Acute Mucosal Infection"},
            {"112","Analysis Of Saliva Sample"},
            {"113","Band 1 Referral for Advanced Mandatory Treatment"},
            {"114","Band 2 Referral for Advanced Mandatory Treatment"},
            {"115","Band 3 Referral for Advanced Mandatory Treatment"},
            {"116","Diagnostic Wax Up"},
            {"117","Dry Socket"},
            {"118","Study Models"},
            {"119","Treatment of Infected Sockets"},
            {"120","Incising an Abscess"},
            {"200","Scale & Polish"},
            {"201","Periodontal Scaling And Root Planing"},
            {"202","Hygiene 20"},
            {"203","Hygiene 30"},
            {"204","Hygiene 45"},
            {"205","Hygiene 60"},
            {"206","Full Mouth Debridement"},
            {"207","Tooth Dressing"},
            {"208","Crown Lengthening"},
            {"209","Airflow"},
            {"210","Bone Grafting"},
            {"211","Guided Tissue Regeneration"},
            {"212","Subepithelial Connective Tissue Graft"},
            {"213","Splints"},
            {"214","Periodontal Maintenance "},
            {"215","Hygiene Treatment"},
            {"216","Perio-Chip"},
            {"300","Topical Application Of Fluoride Varnish"},
            {"301","Fissure Sealant - Per Tooth"},
            {"400","Amalgam Filling"},
            {"401","Composite Filling"},
            {"402","Temporary Filling"},
            {"403","Glass Ionomer"},
            {"404","Fissure Sealant - Composite"},
            {"405","Fissure Sealant - Glass Ionomer"},
            {"406","Fissure Sealant - Composite & Glass Ionomer"},
            {"407","Inlay Imps & Prep"},
            {"408","Inlay/Onlay - Gold"},
            {"409","Inlay/Onlay - Porcelain/Ceramic"},
            {"410","Inlay/Onlay"},
            {"411","Recement Inlay/Onlay"},
            {"412","Veneer Imps"},
            {"413","Porcelain Veneer"},
            {"414","Crown Imps & Prep"},
            {"415","Crown "},
            {"416","Porcelain Crown"},
            {"417","Porcelain Bonded Crown"},
            {"418","Bonded Crown"},
            {"419","Gold Crown"},
            {"420","Metal Crown"},
            {"421","Temporary Crown"},
            {"422","Recement Crown"},
            {"423","Post & Core"},
            {"424","Recement Post"},
            {"425","Core Buildup, Including Any Pins"},
            {"426","Pin Retention"},
            {"427","Post Removal "},
            {"428","Coping"},
            {"429","Emax Crown"},
            {"430","Zirconium Crown"},
            {"431","Veneer"},
            {"432","Crown Repair"},
            {"500","RCT - Molar"},
            {"501","RCT - Premolar Tooth"},
            {"502","RCT - Incisor"},
            {"503","RCT additional visit"},
            {"504","Re-RCT"},
            {"505","Pulpal Therapy "},
            {"506","Pulpotomy (Excluding Final Restoration) "},
            {"600","Extraction"},
            {"601","Surgical/Wisdom Tooth Extraction"},
            {"602","Suture Removal"},
            {"603","Removal Of Impacted Tooth - Soft Tissue"},
            {"604","Removal Of Impacted Tooth - Partially Bony"},
            {"605","Coronectomy - Intentional Partial Tooth Removal"},
            {"606","Biopsy Of Oral Tissue - Hard (Bone, Tooth)"},
            {"607","Apicectomy/Periradicular Surgery"},
            {"700","Primary Denture Impressions"},
            {"701","Secondary Denture Impressions"},
            {"702","Denture Bite"},
            {"703","Denture Try-in"},
            {"704","Full Upper Acrylic Denture"},
            {"705","Full Lower Acrylic Denture"},
            {"706","Full Upper & Lower Acrylic Denture"},
            {"707","Partial Acrylic Denture"},
            {"708","Full Upper Chrome Denture"},
            {"709","Full Lower Chrome Denture"},
            {"710","Full Upper & Lower Chrome Denture Fit"},
            {"711","Partial Chrome Denture"},
            {"712","Tooth Addition to a Acrylic Denture"},
            {"713","Tooth Addition to a Chrome Denture"},
            {"714","Adjust Denture "},
            {"715","Denture Repair"},
            {"716","Denture Reline"},
            {"717","Soft Lining"},
            {"718","Soft Lining - New Denture"},
            {"719","Tissue Conditioning"},
            {"720","Denture Ease"},
            {"721","Denture"},
            {"800","Implant Consultation"},
            {"801","Placement Of Implant"},
            {"802","Interim Abutment"},
            {"803","Implant Retained Denture"},
            {"804","Connecting Bar for Implant"},
            {"805","Implant Abutment"},
            {"806","Implant Crown"},
            {"807","Implant -  Full Denture"},
            {"808","Implant - Partial Denture"},
            {"809","Implant - Bridge"},
            {"810","Repair Implant Supported Prosthesis"},
            {"811","Debridement Of A Periimplant Defect"},
            {"812","Bone Graft At Time Of Implant Placement"},
            {"813","Implant Review"},
            {"814","Implant Maintenance Procedures"},
            {"900","Bridge Prep"},
            {"901","Bridge Try In"},
            {"902","Bonded Bridge Pontic"},
            {"903","Bonded Bridge Retainer"},
            {"904","Gold Bridge Pontic"},
            {"905","Gold Bridge Retainer"},
            {"906","Porcelain Bridge Pontic"},
            {"907","Porcelain Bridge Retainer"},
            {"908","Porcelain Bonded Bridge Pontic"},
            {"909","Porcelain Bonded Bridge Retainer"},
            {"910","Maryland Bridge"},
            {"911","Maryland Wing"},
            {"912","Clasp"},
            {"913","Recement Bridge"},
            {"914","Stress Breaker"},
            {"915","Precision Attachment"},
            {"916","Bridge Repair"},
            {"917","Bridge Retainer"},
            {"918","Bridge Pontic"},
            {"919","Temporary Bridge Unit"},
            {"920","Bridge"},
            {"1000","Ortho Assessment/Review/Exam"},
            {"1001","Ortho Review"},
            {"1002","Ortho Study Models"},
            {"1004","Ortho Retention"},
            {"1005","Invisalign"},
            {"1006","Removable Upper Appliance"},
            {"1007","Removable Lower Appliance"},
            {"1008","Functional Appliance Fit"},
            {"1009","Fixed Upper Appliance"},
            {"1010","Fixed Lower Appliance"},
            {"1011","Retainer Upper"},
            {"1012","Retainer Lower"},
            {"1013","Ortho Extraction"},
            {"1014","Ortho New Patient Exam"},
            {"1015","Ortho Debond"},
            {"1016","Orthodontic Separators"},
            {"1017","Orthodontic Impressions"},
            {"1018","Ortho Adjustment"},
            {"1019","Ortho Bond up"},
            {"1020","Ortho Retainer Fit"},
            {"1021","Ortho Supervision of Retention"},
            {"1022","Orthodontic Emergency"},
            {"1023","Ortho Replacement Removeable Appliance"},
            {"1024","Ortho Replacement Essix Retainer"},
            {"1025","Ortho Replacement Fixed Retainer"},
            {"1026","Ortho Ceramic Brackets Fixed Appliance Upper"},
            {"1027","Ortho Ceramic Brackets Fixed Appliance Lower"},
            {"1028","Ortho Sectional Steel Appliance"},
            {"1029","Ortho Sectional Ceramic Appliance"},
            {"1030","Ortho  Bonded (Fixed) Retainer"},
            {"1031","Ortho Stage Payment"},
            {"1032","Ortho - Other Orthodontic Treatment"},
            {"1033","Oral/Facial Photographic Images"},
            {"1034","Ortho Photographs"},
            {"1035","Ortho Removable Appliance"},
            {"1040","Functional Appliance Review"},
            {"1041","Repair To An Appliance Fitted By Another Dentist"},
            {"1100","Office Visit - After Regularly Scheduled Hours"},
            {"1101","Case Presentation, Detailed And Extensive Treatment Planning"},
            {"1102","Antibiotic Prescription"},
            {"1103"," Prescription"},
            {"1104","Sensitive Dentine"},
            {"1105","Lucia Jig"},
            {"1106","Bite Guard"},
            {"1107","Mouth Guard"},
            {"1108","Sports Mouthguard"},
            {"1109","Repair And/Or Reline Of Occlusal Guard"},
            {"1110","Occlusion Analysis - Mounted Case"},
            {"1111","Occlusal Adjustment"},
            {"1112","Enamel Microabrasion  "},
            {"1113","In Surgery Bleaching (Whitening)"},
            {"1114","Home Bleaching Kit (Whitening)"},
            {"1115","Bleaching Trays"},
            {"1116","Stone/Smooth Tooth"},
            {"1117","Impressions"},
            {"1118","Payment Refund"},
            {"9975","Discount"},
            {"9976","Caries"},
            {"9977","Root Filled"},
            {"9978","Reset Tooth"},
            {"9979","Tooth Needs to be Extracted"},
            {"9980","Missing Tooth"},
            {"9981","Drifted Right"},
            {"9982","Drifted Left"},
            {"9983","Closed Gap"},
            {"9984","Fractured Tooth"},
            {"9985","Watch Tooth"},
            {"9986","Other Tooth Specific Treatment"},
            {"9987","Opening Balance"},
            {"9988","Deposit for Future Work"},
            {"9989","Decay"},
            {"9990","General Note"},
            {"9991","Partially Erupted Tooth"},
            {"9992","Retained Root"},
            {"9993","Unerupted or exfoliated teeth"},
            {"9994","Arrested Caries"},
            {"9995","Tooth Specific Note"},
            {"9996","Early Caries"},
            {"9997","Cavity"},
            {"9998","Surface Wear (Worn)"},
            {"9999","Other Treatment"}

        };

        public readonly Dictionary<string, string> sco_valid_codes = new Dictionary<string, string>()
        {
            {"P100","Exam"},
            {"P101","Exam & Scale & Polish "},
            {"P102","New Patient Exam"},
            {"P103","Review"},
            {"P104","Assessment & Advice"},
            {"P105","Small Radiograph"},
            {"P106","Intraoral Photographs"},
            {"P107","Panoral Radiograph"},
            {"P108","Cephalometric Radiographic Image"},
            {"P109","Clinical Photographs"},
            {"P110","Periapical X Ray"},
            {"P111","Acute Mucosal Infection"},
            {"P112","Analysis Of Saliva Sample"},
            {"P113","Band 1 Referral for Advanced Mandatory Treatment"},
            {"P114","Band 2 Referral for Advanced Mandatory Treatment"},
            {"P115","Band 3 Referral for Advanced Mandatory Treatment"},
            {"P116","Diagnostic Wax Up"},
            {"P117","Dry Socket"},
            {"P118","Study Models"},
            {"P119","Treatment of Infected Sockets"},
            {"P120","Incising an Abscess"},
            {"P200","Scale & Polish"},
            {"P201","Periodontal Scaling And Root Planing"},
            {"P202","Hygiene 20"},
            {"P203","Hygiene 30"},
            {"P204","Hygiene 45"},
            {"P205","Hygiene 60"},
            {"P206","Full Mouth Debridement"},
            {"P207","Tooth Dressing"},
            {"P208","Crown Lengthening"},
            {"P209","Airflow"},
            {"P210","Bone Grafting"},
            {"P211","Guided Tissue Regeneration"},
            {"P212","Subepithelial Connective Tissue Graft"},
            {"P213","Splints"},
            {"P214","Periodontal Maintenance "},
            {"P215","Hygiene Treatment"},
            {"P216","Perio-Chip"},
            {"P300","Topical Application Of Fluoride Varnish"},
            {"P301","Fissure Sealant - Per Tooth"},
            {"P400","Amalgam Filling"},
            {"P401","Composite Filling"},
            {"P402","Temporary Filling"},
            {"P403","Glass Ionomer"},
            {"P404","Fissure Sealant - Composite"},
            {"P405","Fissure Sealant - Glass Ionomer"},
            {"P406","Fissure Sealant - Composite & Glass Ionomer"},
            {"P407","Inlay Imps & Prep"},
            {"P408","Inlay/Onlay - Gold"},
            {"P409","Inlay/Onlay - Porcelain/Ceramic"},
            {"P410","Inlay/Onlay"},
            {"P411","Recement Inlay/Onlay"},
            {"P412","Veneer Imps"},
            {"P413","Porcelain Veneer"},
            {"P414","Crown Imps & Prep"},
            {"P415","Crown "},
            {"P416","Porcelain Crown"},
            {"P417","Porcelain Bonded Crown"},
            {"P418","Bonded Crown"},
            {"P419","Gold Crown"},
            {"P420","Metal Crown"},
            {"P421","Temporary Crown"},
            {"P422","Recement Crown"},
            {"P423","Post & Core"},
            {"P424","Recement Post"},
            {"P425","Core Buildup, Including Any Pins"},
            {"P426","Pin Retention"},
            {"P427","Post Removal "},
            {"P428","Coping"},
            {"P429","Emax Crown"},
            {"P430","Zirconium Crown"},
            {"P431","Veneer"},
            {"P432","Crown Repair"},
            {"P500","RCT - Molar"},
            {"P501","RCT - Premolar Tooth"},
            {"P502","RCT - Incisor"},
            {"P503","RCT additional visit"},
            {"P504","Re-RCT"},
            {"P505","Pulpal Therapy "},
            {"P506","Pulpotomy (Excluding Final Restoration) "},
            {"P600","Extraction"},
            {"P601","Surgical/Wisdom Tooth Extraction"},
            {"P602","Suture Removal"},
            {"P603","Removal Of Impacted Tooth - Soft Tissue"},
            {"P604","Removal Of Impacted Tooth - Partially Bony"},
            {"P605","Coronectomy - Intentional Partial Tooth Removal"},
            {"P606","Biopsy Of Oral Tissue - Hard (Bone, Tooth)"},
            {"P607","Apicectomy/Periradicular Surgery"},
            {"P700","Primary Denture Impressions"},
            {"P701","Secondary Denture Impressions"},
            {"P702","Denture Bite"},
            {"P703","Denture Try-in"},
            {"P704","Full Upper Acrylic Denture"},
            {"P705","Full Lower Acrylic Denture"},
            {"P706","Full Upper & Lower Acrylic Denture"},
            {"P707","Partial Acrylic Denture"},
            {"P708","Full Upper Chrome Denture"},
            {"P709","Full Lower Chrome Denture"},
            {"P710","Full Upper & Lower Chrome Denture Fit"},
            {"P711","Partial Chrome Denture"},
            {"P712","Tooth Addition to a Acrylic Denture"},
            {"P713","Tooth Addition to a Chrome Denture"},
            {"P714","Adjust Denture "},
            {"P715","Denture Repair"},
            {"P716","Denture Reline"},
            {"P717","Soft Lining"},
            {"P718","Soft Lining - New Denture"},
            {"P719","Tissue Conditioning"},
            {"P720","Denture Ease"},
            {"P721","Denture"},
            {"P800","Implant Consultation"},
            {"P801","Placement Of Implant"},
            {"P802","Interim Abutment"},
            {"P803","Implant Retained Denture"},
            {"P804","Connecting Bar for Implant"},
            {"P805","Implant Abutment"},
            {"P806","Implant Crown"},
            {"P807","Implant -  Full Denture"},
            {"P808","Implant - Partial Denture"},
            {"P809","Implant - Bridge"},
            {"P810","Repair Implant Supported Prosthesis"},
            {"P811","Debridement Of A Periimplant Defect"},
            {"P812","Bone Graft At Time Of Implant Placement"},
            {"P813","Implant Review"},
            {"P814","Implant Maintenance Procedures"},
            {"P900","Bridge Prep"},
            {"P901","Bridge Try In"},
            {"P902","Bonded Bridge Pontic"},
            {"P903","Bonded Bridge Retainer"},
            {"P904","Gold Bridge Pontic"},
            {"P905","Gold Bridge Retainer"},
            {"P906","Porcelain Bridge Pontic"},
            {"P907","Porcelain Bridge Retainer"},
            {"P908","Porcelain Bonded Bridge Pontic"},
            {"P909","Porcelain Bonded Bridge Retainer"},
            {"P910","Maryland Bridge"},
            {"P911","Maryland Wing"},
            {"P912","Clasp"},
            {"P913","Recement Bridge"},
            {"P914","Stress Breaker"},
            {"P915","Precision Attachment"},
            {"P916","Bridge Repair"},
            {"P917","Bridge Retainer"},
            {"P918","Bridge Pontic"},
            {"P919","Temporary Bridge Unit"},
            {"P920","Bridge"},
            {"P1000","Ortho Assessment/Review/Exam"},
            {"P1001","Ortho Review"},
            {"P1002","Ortho Study Models"},
            {"P1004","Ortho Retention"},
            {"P1005","Invisalign"},
            {"P1006","Removable Upper Appliance"},
            {"P1007","Removable Lower Appliance"},
            {"P1008","Functional Appliance Fit"},
            {"P1009","Fixed Upper Appliance"},
            {"P1010","Fixed Lower Appliance"},
            {"P1011","Retainer Upper"},
            {"P1012","Retainer Lower"},
            {"P1013","Ortho Extraction"},
            {"P1014","Ortho New Patient Exam"},
            {"P1015","Ortho Debond"},
            {"P1016","Orthodontic Separators"},
            {"P1017","Orthodontic Impressions"},
            {"P1018","Ortho Adjustment"},
            {"P1019","Ortho Bond up"},
            {"P1020","Ortho Retainer Fit"},
            {"P1021","Ortho Supervision of Retention"},
            {"P1022","Orthodontic Emergency"},
            {"P1023","Ortho Replacement Removeable Appliance"},
            {"P1024","Ortho Replacement Essix Retainer"},
            {"P1025","Ortho Replacement Fixed Retainer"},
            {"P1026","Ortho Ceramic Brackets Fixed Appliance Upper"},
            {"P1027","Ortho Ceramic Brackets Fixed Appliance Lower"},
            {"P1028","Ortho Sectional Steel Appliance"},
            {"P1029","Ortho Sectional Ceramic Appliance"},
            {"P1030","Ortho  Bonded (Fixed) Retainer"},
            {"P1031","Ortho Stage Payment"},
            {"P1032","Ortho - Other Orthodontic Treatment"},
            {"P1033","Oral/Facial Photographic Images"},
            {"P1034","Ortho Photographs"},
            {"P1035","Ortho Removable Appliance"},
            {"P1040","Functional Appliance Review"},
            {"P1041","Repair To An Appliance Fitted By Another Dentist"},
            {"P1100","Office Visit - After Regularly Scheduled Hours"},
            {"P1101","Case Presentation, Detailed And Extensive Treatment Planning"},
            {"P1102","Antibiotic Prescription"},
            {"P1103"," Prescription"},
            {"P1104","Sensitive Dentine"},
            {"P1105","Lucia Jig"},
            {"P1106","Bite Guard"},
            {"P1107","Mouth Guard"},
            {"P1108","Sports Mouthguard"},
            {"P1109","Repair And/Or Reline Of Occlusal Guard"},
            {"P1110","Occlusion Analysis - Mounted Case"},
            {"P1111","Occlusal Adjustment"},
            {"P1112","Enamel Microabrasion  "},
            {"P1113","In Surgery Bleaching (Whitening)"},
            {"P1114","Home Bleaching Kit (Whitening)"},
            {"P1115","Bleaching Trays"},
            {"P1116","Stone/Smooth Tooth"},
            {"P1117","Impresssions"},
            {"P1118","Payment Refund"},
            {"P9975","Discount"},
            {"P9976","Caries"},
            {"P9977","Root Filled"},
            {"P9978","Reset Tooth"},
            {"P9979","Tooth Needs to be Extracted"},
            {"P9980","Missing Tooth"},
            {"P9981","Drifted Right"},
            {"P9982","Drifted Left"},
            {"P9983","Closed Gap"},
            {"P9984","Fractured Tooth"},
            {"P9985","Watch Tooth"},
            {"P9986","Other Tooth Specific Treatment"},
            {"P9987","Opening Balance"},
            {"P9988","Deposit for Future Work"},
            {"P9989","Decay"},
            {"P9990","General Note"},
            {"P9991","Partially Erupted Tooth"},
            {"P9992","Retained Root"},
            {"P9993","Unerupted or exfoliated teeth"},
            {"P9994","Arrested Caries"},
            {"P9995","Tooth Specific Note"},
            {"P9996","Early Caries"},
            {"P9997","Cavity"},
            {"P9998","Surface Wear (Worn)"},
            {"P9999","Other Treatment"},
            {"10101","Routine Examination"},
            {"11101","Extensive Examination"},
            {"12101","Full Case Assessment"},
            {"141","Residential / Domiciliary Clinical Examination"},
            {"14101","Residential / Domiciliary Clinical Examination"},
            {"151","Extensive Examination (General)"},
            {"161","Extensive Examination (Ortho)"},
            {"171","Simple assessment (Ortho)"},
            {"181","Simple assessment (General)- Trauma Exam only"},
            {"20001","OPT Analysis"},
            {"201","Small Xray"},
            {"202","Medium Xray"},
            {"203","Large Xray"},
            {"20401","Panoral Xray"},
            {"205","Lateral Headplate (Ortho)"},
            {"20601","Lateral Headplate"},
            {"20701","Duplication of panoral films and/or lateral headplates"},
            {"211","Study Cast (per set)"},
            {"212","Study Cast (per duplicate set)"},
            {"213","Study Cast (per single cast)"},
            {"22101","Occlusal Analysis"},
            {"22102","Adjustable Articulator"},
            {"301","Colour Photograph"},
            {"601","Intensive Hygiene Instruction"},
            {"701","Fissure Sealants of Unfilled 3rd Molars"},
            {"711","Topical Fluoride Application (Special Needs)"},
            {"100101","Scaling"},
            {"101101","Scaling  requiring 2 or more visits"},
            {"1021","Intensive Scaling Including Periodontal Charting"},
            {"1022","Sextant"},
            {"104105","Splinting of periodontally compromised teeth (one union)"},
            {"104106","Splinting of periodontally compromised teeth (two unions)"},
            {"104107","Splinting of periodontally compromised teeth (three unions)"},
            {"104108","Splinting of periodontally compromised teeth (four or more unions)"},
            {"1100","11[A]/[B] Additional Each Sextant"},
            {"1101","Gingivectomy, 1st 2 Adjacent Teeth in 1 Jaw"},
            {"1102","Gingivectomy, 1st 2 Adjacent Teeth in 1 Jaw"},
            {"1103","11[A] Additional Tooth"},
            {"1111","Raising Flaps, Curretage etc"},
            {"1112","Raising Flaps, Curretage etc"},
            {"1113","11[B] Additional Tooth"},
            {"1121","Gingival Graft"},
            {"1131","Excision of Soft Tissue to Lengthen Crown of Tooth"},
            {"119201","Single Tooth Gingivectomy"},
            {"1401","Amalgam Filling in a Single Surface"},
            {"1402","Two or More Amalgam Fillings in the Same Tooth"},
            {"1403","Two or More Amalgam Fillings in the Same Tooth MO or DO"},
            {"1404","Three or More Amalgam Fillings in the Same Tooth MOD"},
            {"1411","Tunnel Restoration MO or DO"},
            {"1412","Tunnel Restoration MOD"},
            {"1420","Composite Resin Filling Two or More in the Same Tooth"},
            {"1421","Composite Resin Filling"},
            {"1422","Acid Etch 1 Incisal Angle MI"},
            {"1423","Acid Etch 1 Incisal Edge I"},
            {"1424","Acid Etch 2 Incisal Angles MID"},
            {"1425","Additional Fee for Buccal Cusp"},
            {"1426","GI Filling 3m(g)"},
            {"1427","GI Filling in Two Surfaces 3d(g)3m(g)"},
            {"1428","Retained deciduous teeth. Filling including any dressing, pulp capping  & pin or screw or acid etch & other prep work"},
            {"1431","Pin or Screw Retention"},
            {"1445","Stabilisation Filling in Suitable Material Without Use of Aerosol Generated Procedure"},
            {"1446","14[E][ii]"},
            {"1452","Removal of Amalgam & Replacing Resin Single Surface"},
            {"1453","Removal of Amalgam & Replacing Resin MO or DO"},
            {"1454","Removal of Amalgam & Replacing with Resin MOD"},
            {"1461","Treatment of Permanent Tooth Using GI, Single Filling 1m or 1mi"},
            {"1462","Treatment of Permanent Tooth Using GI, Double Filling 1m or 1mi"},
            {"1470","Maximum Fee for Combination of Fillings Without Pins, Acid Etch or Buccal Cusp"},
            {"1471","Maximum Fee for Combination of Fillings With Pins, Acid Etch or Buccal Cusp"},
            {"1481","Application of Fissure Sealant with Sealant Only, 5 or More Teeth Requires Prior Approval"},
            {"1482","Application of Fissure Sealant with Composite Resin"},
            {"1483","Application of Fissure Sealant with Glass Ionomer and Composite Resin"},
            {"1501","Endodontic Treatment Incisor or Canine"},
            {"1502","Endodontic Treatment Upper Premolar"},
            {"1503","Endodontic Treatment Lower Premolar"},
            {"1504","Endodontic Treatment Molar Tooth"},
            {"1511","Vital Pulpotomy of a Permanent Tooth"},
            {"1521","Apicectomy of a Permanent Tooth, Incisor or Canine"},
            {"1522","Apicectomy of a Permanent Tooth, Premolar"},
            {"1523","Apicectomy of a Permanent Tooth, Buccal Root(s) of Upper Molar"},
            {"1531","Apicectomy on an upper molar tooth, 1 palatal root only"},
            {"1534","Apicectomy on a lower molar tooth, 1 root"},
            {"1541","Retrograde Root Filling"},
            {"1551","Endodontic Treatment of a Retained Deciduous Tooth"},
            {"160001","Additional fee for first or only Veneer provided "},
            {"1601","Porcelain Veneer"},
            {"1602","Refixing or Recementing a Porcelain Veneer Including All Associated Attention"},
            {"1700","First or Only Inlay/Crown in the Same Jaw"},
            {"1701","Inlay 60% or More Fine Gold, One Surface Cavity"},
            {"1702","Inlay 60% or More Fine Gold, Two Surface Cavity"},
            {"1703","Inlay 60% or More Fine Gold, Two Surface Cavity Involving Incisal Angle"},
            {"1704","Inlay 60% or More Fine Gold, Three or More Surface Cavities"},
            {"1711","Crown or Full Jacket Cast in Precious Metal Alloy"},
            {"1712","Crown Full or Jacket Cast in Non-precious Metal Alloy"},
            {"1716","Crown Porcelain Jacket"},
            {"1721","Bonded Porcelain Precious Metal Crown Anterior Teeth"},
            {"1722","Bonded Porcelain Non Precious Metal Crown Anterior Teeth"},
            {"1723","Crown Porcelain Jacket Thermally Bonded to Wrought Platinum Coping"},
            {"1726","Crown Acrylic Jacket Crown"},
            {"1732","Core & Post Cast in Non-precious Metal Alloy"},
            {"1733","Core & Post Prefabricated in Non-precious Metal Alloy"},
            {"1734","Pin or Screw Retention"},
            {"1735","Inlay, Facing in GI or Resin"},
            {"1736","Crown, Facing in GI or Resin"},
            {"1738","Laboratory Produced Dovetail/Slot in a Crown"},
            {"1739","Laboratory Produced Parallel Metallic Surface of a Crown"},
            {"1742","Temporary Crown"},
            {"1743","Temporary Crown, Post Retained"},
            {"1744","Removal of a Post"},
            {"1750","First or only Crown in the Same Jaw"},
            {"1752","Three Quarter Crown (Non-Precious Metal)"},
            {"1753","1 Crown (Full or Jacket crown stainless steel prefabricated)"},
            {"1761","Repair of an Inlay"},
            {"1762","Repair of a Crown"},
            {"1770","First or only Crown in the Same Jaw"},
            {"1772","Removal of a Crown (Prior to Repair)"},
            {"1773","Insertion of a Pin/screw (F4) + recementing crown"},
            {"1774","Insertion of core & Post prefabricated in non-precious metal (F3) + recementing crown"},
            {"1775","Insertion of a Kurer crown saver or cast metal Post (F2) + recementing crown"},
            {"1776","Dentine Bonded Core on Root treated molar Teeth"},
            {"1781","Refixing/Recementing an Inlay"},
            {"1782","Refixing/Recementing a Crown"},
            {"1801","Bridge, Compound Cavity"},
            {"1802","Bridge, Compound Confluent Cavity or Three-Quarter Crown"},
            {"1803","Bridge, Full or Jacket Crown"},
            {"1804","Bridge, Full or Jacket Crown Cast in Precious Metal"},
            {"1805","Bridge, Full or Jacket Crown Cast in Non-Precious Metal"},
            {"1806","Bridge, Porcelain or Jacket Crown"},
            {"1807","Bridge, Bonded Retainers"},
            {"1808","Bridge, Full or Jacket Crown Cast in Alloy of Non-Precious Metal"},
            {"1811","Bridge, Core and Post Cast in Precious Metal Alloy"},
            {"1812","Bridge, Core and Post Cast in Non-Precious Metal Alloy"},
            {"1813","Bridge, Core and Post Prefabricated in Non-Precious Metal Alloy"},
            {"1814","Bridge, Pin or Screw Retention"},
            {"181509","Bridge Laboratory constructed dovetail (One Tooth)"},
            {"181510","Bridge Laboratory constructed dovetail (Two Teeth)"},
            {"1816","Bridge, Lab. Processed Composite Facing in Connection with 18[A]1 or 18[A]2"},
            {"1821","Bridge, Cast Alloy Containing 60% or More Fine Gold"},
            {"1822","Bridge, Precious Metal"},
            {"1823","Bridge, Non-Precious Metal"},
            {"1824","Bridge, Porcelain"},
            {"1825","Bridge, Porcelain Bonded to an Alloy of Fine Gold or Precious Metal"},
            {"1826","Bridge, Porcelain Bonded to an Alloy of Non-Precious Metal"},
            {"1827","Bridge, Lab. Processed Composite Facing in Connection with Pontics Under 18[C]1 & 18[C]2"},
            {"1831","Retainer in Cast Metal"},
            {"1832","Bridge, Pontic in Thermally Bonded Porcelain"},
            {"184129","Spring Cantilever Arm - 60% or more fine gold"},
            {"184130","Spring Cantilever Arm - Precious Metal"},
            {"184131","Spring Cantilever Arm - Non-Precious Metal"},
            {"184133","Burnout Attachment - Tubelock attachment"},
            {"1851","Bridge Fabricated in Laboratory for Bridges to be Retained for 3 mths+"},
            {"1852","Temporary Bridge"},
            {"1861","Recementing an Acid Etch Retained Bridge (Maryland)"},
            {"1862","Recementing or Fixing a Bridge"},
            {"187101","Removal or sectioning of a bridge prior to repair"},
            {"187107","One Unit (Repair of precious metal Bridge by rebonding porcelain of retainer &/or Pontic(s)"},
            {"187108","Two Units (Repair of precious metal Bridge by rebonding porcelain of retainer &/or Pontic(s)"},
            {"187109","Three Units (Repair of precious metal Bridge by rebonding porcelain of retainer &/or Pontic(s)"},
            {"187123","Veneer of Bridge repair (includes additional fee)"},
            {"187124","Dentine Bonded Core for Bridges on Root Filled Molars"},
            {"187125","Insertion of 2 pin / screw / preformed post + Recementing original Bridge"},
            {"187126","Insertion of 2 cast precious metal core + post and Recementing original Bridge"},
            {"187127","Insertion of 2 cast non-precious metal core + post including Radix Anchor and Kurer Crown Saver + Recementing original Bridge"},
            {"187128","Insertion of 2 core + post prefabricated in non-precious metal + Recementing original Bridge"},
            {"187201","Insertion of pin/screw/performed post + recementing original bridge"},
            {"187301","Insertion of cast precious metal core + post & recementing original bridge"},
            {"187401","Insertion of non-precious metal core + post including Radix Anchor & Kurer Crown Saver + Rec. original bridge"},
            {"187501","Insertion of core + post prefabricated in non-precious metal + recementing original bridge"},
            {"1881","Replacement Bridge (Fab. in Lab) without use of aerosol generating procedure"},
            {"1882","Replacement Bridge (Any Bridge Other Than 18[I][1]) without use of aerosol generating procedure"},
            {"2101","Extraction of Permanent Teeth"},
            {"2102","Extraction of Deciduous Teeth"},
            {"2121","Extractions Additional Fee for Visit"},
            {"2201","Extraction Involving Soft Tissue Only"},
            {"2202","Extraction Involving Bone Removal for Incisors or Canines"},
            {"2203","Extraction Involving Bone Removal for Premolars or Molars"},
            {"2204","Extraction of Impacted Upper 3rd Molar, Not Requiring Division of Roots or Crowns"},
            {"2205","Extraction of Impacted Upper 3rd Molar, Requiring Division of Roots or Crowns"},
            {"2206","Extraction of Impacted Lower 3rd Molar, Not Requiring Division of Roots or Crowns"},
            {"2207","Extraction of Impacted Lower 3rd Molar, Requiring Division of Roots or Crowns"},
            {"221101","Fraenectomy"},
            {"222139","Removal of Operculum"},
            {"222141","Removal of Papilloma or Fibroma"},
            {"222142","Removal of mucocoele"},
            {"222143","Closure of oro-antral communication by means of a buccal advancement flap"},
            {"222144","Closure of oro-antral communication by means of a palatal flap"},
            {"222145","Repair of lateral perforation in connection with items 1521/1541"},
            {"222146","Surgical removal of unerupted mesiodens ,odontome or supernumerary involving raising of a surgical flap and bone removal."},
            {"2222","Surgical exposure of unerupted canine or second premolar teeth – buccal flap, soft tissue only"},
            {"2223","Surgical exposure of unerupted canine or second premolar teeth – palatal flap, soft tissue only"},
            {"2224","Surgical exposure of unerupted canine or second premolar teeth – buccal flap, bone removal"},
            {"2225","Surgical exposure of unerupted canine or second premolar teeth-palatal flap, bone removal"},
            {"2226","Surgical removal of impacted canine or upper second premolar teeth – buccal flap, bone removal"},
            {"2227","Surgical removal of impacted canine or upper second premolar teeth – palatal flap, bone removal"},
            {"2228","Surgical removal of impacted lower second premolar teeth"},
            {"2229","Coronectomy of lower third molar teeth involving raising of a flap, bone removal and crown sectioning."},
            {"2301","Arrest of Haemorrhage Other Than 23[A][2] &/or 23[B]"},
            {"2302","Removal of Plugs and/or Sutures"},
            {"2311","Treatment of Infected Sockets"},
            {"2551","Sedation Visit where the number of teeth extracted is 1-4"},
            {"2552","Sedation Visit where the number of teeth extracted is 5-9"},
            {"2553","Sedation Visit where the number of teeth extracted is 10-16"},
            {"2554","Sedation Visit where the number of teeth extracted is 17+"},
            {"2555","Sedation Visit where the cost of trt. carried out under Sedation is up to & including £10"},
            {"2556","Sedation Visit where the cost of trt. carried out under Sedation is between £10.01 & £25"},
            {"2557","Sedation Visit where the cost of trt. carried out under Sedation is between £25.01 & £50"},
            {"2558","Sedation Visit where the cost of trt. carried out under Sedation is greater than £50.00"},
            {"2560","Sedation Maximum per course of treatment."},
            {"256108","Sedation For patients in Cap. , Trt. other than Item 21 Extraction. Where cost of treatment carried out under sedation at that visit is greater than £50.00"},
            {"256301","Sedation in connection with trt. involving the prep. & fitting Veneers, Inlays, Crowns or Bridge Retainers"},
            {"2566","Additional Sedation Fee for Anaesthetist Being Called to Surgery < 1.61km/1 mile"},
            {"2567","Additional Sedation Fee for Anaesthetist Being Called to Surgery >=1.61km/1 mile"},
            {"2573","Visit Inhalation Provided, in Cases of Physical or Mental Handicap, or Anxiety"},
            {"2574","Visit Injection Provided, in Cases of Physical or Mental Handicap, or Anxiety"},
            {"2701","Occlusal Pivots"},
            {"2711","Visit Tissue Conditioners"},
            {"2712","Visit Tissue Conditioners"},
            {"273001","F/F Denture (Initial Supply/Replacement)"},
            {"273101","Full Upper Denture"},
            {"273201","Full Lower Denture"},
            {"2733","Partial Upper Denture"},
            {"273401","Additional fee for stainless steel lingual or palatal bar"},
            {"2735","Partial Lower Denture"},
            {"273801","Max Fee Combinations of Upper & Lower Dentures"},
            {"274101","F/- Denture (Chrome cobalt or stainless steel)"},
            {"274201","-/F Denture (Chrome cobalt or stainless steel)"},
            {"2743","P/- Denture Horse Shoe, Plate Design"},
            {"2744","P/- Denture Skeleton Design With Single Connecting Bars"},
            {"2745","P/- Denture Skeleton Design With Multiple Connecting Bars"},
            {"2746","Additional Denture Fee for Backing"},
            {"2747","-/P Denture Horse Shoe, Plate Design"},
            {"2748","-/P Denture Skeleton Design With Single Connecting Bars"},
            {"2749","-/P Denture Skeleton Design With Multiple Connecting Bars"},
            {"276101","Provision of soft lining where the  denture is provided at the same time Upper"},
            {"276201","Provision of soft lining where the  denture is provided at the same time Lower"},
            {"277101","Upper (Laboratory constructed Special Trays)"},
            {"277201","Lower (Laboratory constructed Special Trays)"},
            {"278101","Upper (Inclusion of a perm. Patient Identification Marker)"},
            {"278201","Lower (Inclusion of a perm. Patient Identification Marker)"},
            {"2801","Repair - Crack/Fracture or Refixing ot Providing & Fixing a replacement Tooth Upper"},
            {"2802","Repair - Crack/Fracture or Refixing ot Providing & Fixing a replacement Tooth Lower"},
            {"2803","Repair - Refixing a Clasp or Providing & Fixing a replacement Clasp Upper"},
            {"2804","Repair - Refixing a Clasp or Providing & Fixing a replacement Clasp lower"},
            {"281001","Maximum repair fee per Upper Denture"},
            {"281107","Soldering or Welding Repairs (Stainless steel or chrome cobalt)"},
            {"282001","Maximum repair fee per Lower Denture"},
            {"282101","Additional fee for Impression (Upper)"},
            {"282201","Additional fee for Impression (Lower)"},
            {"283101","Adjusting an Upper Denture"},
            {"283201","Adjusting a Lower Denture"},
            {"284101","Simple adjustments to acrylic element"},
            {"284104","Denture bearing 1-3 teeth (Stripping & re-assembling the polymer & teeth)"},
            {"284105","Denture bearing 4-8 teeth (Stripping & re-assembling the polymer & teeth)"},
            {"284106","Denture bearing 9 or more teeth (Stripping & re-assembling the polymer & teeth)"},
            {"284107","Full Denture (Stripping & re-assembling the polymer & teeth)"},
            {"285101","Relining or rebasing an Upper Denture"},
            {"285201","Relining or rebasing a Lower Denture"},
            {"285301","Relining or rebasing with addition of a labial and/or buccal flange (Upper)"},
            {"285401","Relining or rebasing with addition of a labial and/or buccal flange (Lower)"},
            {"285501","Provision or renewal of  Soft lining of an existing Denture (Upper)"},
            {"285601","Provision or renewal of  Soft lining of an existing Denture (Lower)"},
            {"2861","Addition of Clasp (Upper)"},
            {"2862","Addition of Clasp (Lower)"},
            {"2863","Addition of a Tooth (Upper)"},
            {"2864","Addition of a Tooth (Lower)"},
            {"286501","Addition of a new Gum not associated with an addition under 28(D)(1) or (2) (Upper)"},
            {"286601","Addition of a new Gum not associated with an addition under 28(D)(1) or (2) (Lower)"},
            {"287114","Reconstruction of a metal denture (stripping fee)"},
            {"287115","Soldering or Welding (Stainless steel or chrome cobalt)"},
            {"288001","Additional Clasp (Must be claimed with 2880 02)"},
            {"288002","1 Repair (Fracture) Balance Fee (Must be claimed with 2880 01)"},
            {"288004","1 Repair (Fracture) Balance Fee (Must be claimed with 2882 01)"},
            {"288005","Additional Gum (Must be claimed with 2880 06)"},
            {"288006","1 Repair (Fracture) Balance Fee (Must be claimed with 2880 05)"},
            {"288007","Additional Clasp (Must be claimed with 2880 08)"},
            {"288008","2 or More Repairs Balance Fee (Must be claimed with 2880 07)"},
            {"288010","2 or More Repairs Balance Fee (Must be claimed with 2883 01)"},
            {"288011","Additional Gum (Must be claimed with 2880 12)"},
            {"288012","2 or More Repairs Balance Fee (Must be claimed with 2880 11)"},
            {"288013","Additional Clasp (Must be claimed with 2880 14)"},
            {"288014","Refix Clasp Balance Fee Must be claimed with 2880 13)"},
            {"288016","Refix Clasp Balance Fee (Must be claimed with 2881 01)"},
            {"288017","Additional Gum (Must be claimed with 2880 18)"},
            {"288018","Refix Clasp Balance Fee (Must be claimed with 2880 17)"},
            {"288019","Any 2 additions with or without repairs (Max)"},
            {"288101","Additional Tooth (Must be claimed with 2880 16)"},
            {"288201","Additional Tooth (Must be claimed with 2880 04)"},
            {"288301","Additional Tooth (Must be claimed with 2880 10)"},
            {"292101","Provision of emergency splinting"},
            {"2922","Union - Provision of Acid Etch Retained Composite Splint"},
            {"292301","Additional fee for metal bar or wire insert in conjunction with 29(C)(2)"},
            {"2924","Provision of Laboratory Fabricated Heat Cured Acrylic Splint to be Retained for 6+ Weeks"},
            {"2925","Provision of Cast Metal Splint to be Retained for 3+ Months"},
            {"292607","Provision of Maryland Splint 2 Units"},
            {"292608","Provision of Maryland Splint 3 Units"},
            {"292609","Provision of Maryland Splint 4 Units"},
            {"292610","Provision of Maryland Splint 5 or more Units"},
            {"294101","Acrylic Occlusal Appliance"},
            {"2942","Provision of a Laboratory Processed Pressure-Formed Soft Occlusal Appliance"},
            {"299101","Denture Base Polymer Appliance carrying No Teeth"},
            {"299147","Full upper or lower Training Base"},
            {"3201","Upper Removable Spring and/or Screw Type Appliance"},
            {"3202","Lower Removable Spring and/or Screw Type Appliance"},
            {"3203","Upper Simple Fixed Type Appliance"},
            {"3204","Lower Simple Fixed Type Appliance"},
            {"3205","Upper Fixed Multiband or Multibracket Appliance"},
            {"3206","Lower Fixed Multiband or Multibracket Appliance"},
            {"3207","Functional Appliance"},
            {"3211","Upper Bite Plane Appliance"},
            {"3212","Lower Bite Plane Appliance"},
            {"322101","Upper (Extra-Oral Traction)"},
            {"322201","Upper Anchorage Reinforcement"},
            {"322301","Lower (Extra-Oral Traction)"},
            {"322401","Lower Anchorage Reinforcement"},
            {"323001","Repair of a removable functional appliance"},
            {"323101","Supervision of Retention for a period of not less than 5 months."},
            {"3232","Supervision of Retention for an Additional Period of Not Less Than 2 Months"},
            {"323301","Upper Removable Retainer in Acrylic Resin"},
            {"323401","Lower Removable Retainer in Acrylic Resin"},
            {"323501","Upper Fixed or Bonded Retainer"},
            {"323601","Lower Fixed or Bonded Retainer"},
            {"323701","Upper Removable Pressure Formed Retainer"},
            {"323801","Lower Removable Pressure Formed Retainer"},
            {"323980","Lower Repair of a Fixed App. involving the replace. of 2 or more bracket bands/archwires"},
            {"324080","Upper Repair of a Fixed App. involving the replace. of 2 or more bracket bands/archwires"},
            {"324101","Upper Repair - Cracks or fractures in the acrylic of a removable appliance"},
            {"3242","Upper Repair - Metal comp. or providing & fixing a metal comp. on a removable appliance"},
            {"324501","Additional fee for an Upper Impression"},
            {"324601","Additional fee for an Lower Impression"},
            {"324701","Lower Repair - Cracks or fractures in the acrylic of a removable appliance"},
            {"3248","Lower Repair - Metal comp. or providing & fixing a metal comp. on a removable appliance"},
            {"325001","Upper Maximum Repair Fee"},
            {"325101","Lower Maximum Repair Fee"},
            {"3261","Addition of a Tooth to an Upper Fixed Appliance or Retainer"},
            {"3262","Addition of a Tooth to a Lower Fixed Appliance or Retainer"},
            {"3263","Addition of a Tooth to an Upper Removable Appliance or Retainer"},
            {"3264","Addition of a Tooth to a Lower Removable Appliance or Retainer"},
            {"3281","Replacement Space Maintainer or Retention Appliance"},
            {"3282","Replacement Removable Spring and/or Screw Type Appliance"},
            {"3283","Replacement Simple Fixed Type Appliance"},
            {"3284","Replacement Fixed Multiband or Multibracket Appliances"},
            {"3285","Replacement of Functional Appliances"},
            {"329002","Active removable appliance (Made and fitted)"},
            {"329003","Active removable appliance per visit"},
            {"329004","Active removable appliance per visit"},
            {"329005","Active removable appliance per visit"},
            {"329006","Active removable appliance per visit"},
            {"329007","Simple fixed appliance (Quad Helix) (Made but not fitted)"},
            {"329008","Simple fixed appliance (Quad Helix) (Made and fitted)"},
            {"329009","Simple fixed appliance (Quad Helix) (Max Fee)"},
            {"329010","Multiband fixed appliance (Made but not fitted)"},
            {"329011","Multiband fixed appliance (Made and fitted)"},
            {"329012","Multiband fixed appliance per visit"},
            {"329013","Multiband fixed appliance per visit"},
            {"329014","Multiband fixed appliance per visit"},
            {"329015","Multiband fixed appliance per visit"},
            {"329016","Multiband fixed appliance per visit"},
            {"329017","Multiband fixed appliance per visit"},
            {"329018","Multiband fixed appliance per visit"},
            {"329019","Multiband fixed appliance per visit"},
            {"329020","Multiband fixed appliance per visit"},
            {"329021","Multiband fixed appliance per visit"},
            {"329022","Extra oral traction with bands at 6/6 (Made and fitted)"},
            {"329023","Extra oral traction with bands at 6/6) per visit"},
            {"329024","Extra oral traction with bands at 6/6) per visit"},
            {"329025","Extra oral traction with bands at 6/6) per visit"},
            {"329026","Functional appliances (Made but not fitted)"},
            {"329027","Functional appliances (Made and fitted)"},
            {"329028","Functional appliances per visit"},
            {"329029","Functional appliances per visit"},
            {"329030","Functional appliances per visit"},
            {"329031","Functional appliances per visit"},
            {"329032","Bite Plate - Made not fitted"},
            {"329033","Bite Plate - Made and fitted"},
            {"329102","Replacement of one half of twin block functional appliance"},
            {"329103","Reset a twin block functional appliance"},
            {"329109","Interim Payment"},
            {"329110","Interim Payment"},
            {"329111","Interim Payment"},
            {"329121","Cemented inclined plane (Passive traction or deterrent)"},
            {"329122","Space maintainer (Passive traction or deterrent)"},
            {"329125","Bond (Recementing bonded retainer)"},
            {"329126","Bond (Recementing bonded retainer)"},
            {"329141","Ceph not taken by the Dentist providing analysis"},
            {"329181","Hyrax Screw (Rapid Maxillary Expansion)"},
            {"329182","Enamel Stripping/Discing per visit (One visit)"},
            {"329183","Enamel Stripping/Discing per visit (Two visits)"},
            {"329184","Enamel Stripping/Discing per visit (Three or more visits)"},
            {"329191","Interim Payment Recovery"},
            {"329192","Interim Payment Recovery"},
            {"329193","Interim Payment Recovery"},
            {"329201","Active removable appliance (Made but not fitted) Lower"},
            {"329202","Active removable appliance (Made and fitted) Lower"},
            {"329203","Active removable appliance per visit Lower"},
            {"329204","Active removable appliance per visit Lower"},
            {"329205","Active removable appliance per visit Lower"},
            {"329206","Active removable appliance per visit Lower"},
            {"329207","Simple fixed appliance (Quad Helix) (Made but not fitted) Lower"},
            {"329208","Simple fixed appliance (Quad Helix) (Made and fitted) Lower"},
            {"329209","Simple fixed appliance (Quad Helix) (Max Fee) Lower"},
            {"329210","Multiband fixed appliance (Made but not fitted) Lower"},
            {"329211","Multiband fixed appliance (Made and fitted) Lower"},
            {"329212","Multiband fixed appliance per visit Lower"},
            {"329213","Multiband fixed appliance per visit Lower"},
            {"329214","Multiband fixed appliance per visit Lower"},
            {"329215","Multiband fixed appliance per visit Lower"},
            {"329216","Multiband fixed appliance per visit Lower"},
            {"329217","Multiband fixed appliance per visit Lower"},
            {"329218","Multiband fixed appliance per visit Lower"},
            {"329219","Multiband fixed appliance per visit Lower"},
            {"329220","Multiband fixed appliance per visit Lower"},
            {"329221","Multiband fixed appliance per visit Lower"},
            {"329222","Extra oral traction with bands at 6/6 (Made and fitted) Lower"},
            {"329223","Extra oral traction with bands at 6/6) per visit Lower"},
            {"329224","Extra oral traction with bands at 6/6) per visit Lower"},
            {"329225","Extra oral traction with bands at 6/6) per visit Lower"},
            {"329232","Bite Plate - Made not fitted Lower"},
            {"329233","Bite Plate - Made and fitted Lower"},
            {"3501","Domiciliary Visit < 16.1km/10 miles"},
            {"3502","Domiciliary Visit 16.1km/10 miles to 64.4km/40 miles"},
            {"3503","Domiciliary Visit > 64.4km/40 miles"},
            {"3511","Recalled Attendance < 1.61km/1 mile"},
            {"3512","Recalled Attendance > 1.61km/1 mile"},
            {"3601","Taking of Material for Pathological or Bacteriological Exam"},
            {"3611","Stoning or Smoothing"},
            {"3631","Sensitive Cementum or Dentine"},
            {"3641","Issue of a Prescription"},
            {"3651","Reimplantation of a Luxated Tooth Following Trauma"},
            {"3661","Removal of the Fractured Portion of a Natural Tooth"},
            {"3671","Removal of the Coronal Portion & the Shaping/Prep. of the Root Face"},
            {"3701","Treatment of Acute Conditions"},
            {"3801","Stabilising of tooth with a non-amalgam filling (pregnant+ nursing mother)"},
            {"3802","Addition of composite resin to Teeth where an appropriate SDR fee is not available - No tooth preparation necessary"},
            {"3803","Addition of composite resin to Teeth where an appropriate SDR fee is not available - Tooth preparation necessary"},
            {"3804","Addition of composite resin to Teeth where an appropriate SDR fee is not available - Composite build up"},
            {"3805","Addition of composite resin to Teeth where an appropriate SDR fee is not available - Extensive restoration"},
            {"3806","Indirect Composite Veneer"},
            {"3807","Porcelain Veneers on Teeth other than - Upper 321/123 (First veneer in arch)"},
            {"3809","Precious Bonded Crown - Metal/ceramic crown on a molar tooth (includes first crown in arch fee)"},
            {"3810","Non Precious Bonded Crown - Metal/ceramic crown on a molar tooth (includes first crown in arch fee)"},
            {"3811","Laboratory constructed temporary Crown"},
            {"3812","Single surface cavity (Inlays/Pinlays - Precious Metal)"},
            {"3813","Compound cavity (Inlays/Pinlays - Precious Metal)"},
            {"3814","Confluent compound cavity (Inlays/Pinlays - Precious Metal)"},
            {"3815","Single surface cavity (Inlays/Pinlays - Non-Precious Metal)"},
            {"3816","Compound cavity (Inlays/Pinlays - Non-Precious Metal)"},
            {"3817","Confluent compound cavity (Inlays/Pinlays - Non-Precious Metal)"},
            {"3818","Porcelain Inlays MO/DO"},
            {"3819","Porcelain Inlays MOD"},
            {"3820","Indirect Composite Inlay MO/DO"},
            {"3821","Indirect Composite Inlay MOD"},
            {"3822","First or only Inlay per arch"},
            {"382301","Provision of a 'Lucia' jig"},
            {"3824","Relining/rebasing or provision/renewal of soft lining with material polymerised in the mouth, including tissue cond."},
            {"382501","Provision of a Custom Incisal Guide Table"},
            {"3826","Post-retained diaphragm (60% or more fine gold)"},
            {"3827","Post-retained diaphragm (Precious metal)"},
            {"3828","Post-retained diaphragm (Non-precious metal)"},
            {"3829","Gold Coping (60% or more fine gold)"},
            {"3830","Gold Coping (Precious metal)"},
            {"3831","Diagnostic wax-ups per tooth"},
            {"3832","Re-implantation of a tooth removed by Trauma and treatment to root canal"},
            {"3833","Attention to socket - replacing tooth & temporary wiring or splinting - per unit"},
            {"3834","Attention to socket - replacing tooth & temporary wiring or splinting - per unit + fee for temp. splint"},
            {"3835","Use of a natural crown as a Bridge pontic sectioning crown from root"},
            {"3836","Use of a natural crown as a Bridge pontic attention to pulp chamber"},
            {"3837","Use of a natural crown as a Bridge pontic acid etch splinting of Teeth (Per Splint)"},
            {"3838","Indirect Composite / Porcelain onlay"},
            {"3839","60% or more fine gold onlay"},
            {"3840","Precious metal alloy onlay"},
            {"3841","Non Precious metal alloy onlay"},
            {"3842","Ceramic Onlay"},
            {"3843","Abrasion of enamel opacities in vital Teeth per arch"},
            {"3844","Gold Shims"},
            {"3845","Shims - Precious Metal Alloy"},
            {"3846","Shims - NON Precious Metal Alloy"},
            {"3847","Carbon Fibre Posts"},
            {"3848","Internal Bleaching of a non-vital tooth"},
            {"3849","Full coverage in cases of gross tissue loss/malformed Incisors/Peg shaped laterals"},
            {"3850","Refacing of labial surfaces of a tooth in cases of hypoplasia etc."},
            {"385101","Hypnosis first or only visit"},
            {"385201","Hypnosis second visit"},
            {"385301","Hypnosis third or subsequent visit(s)"},
            {"385401","Anatomical articulation with Face Bow transfer"},
            {"3855","Supply and Bond Non Precious Metal Pad and Chain"},
            {"3856XX","Supply and Bond Precious Metal Pad and Chain"},
            {"3857","Bond Pad and Chain supplied by orthodontist"},
            {"3858","Provision of Upper & Lower Study casts & articulation in cases of TMJ Dysfunction"},
            {"385901","Provision of a duplicate single Study cast"},
            {"3860","Incomplete cast metal post and core"},
            {"3861","eOrtho Transfer Case"},
            {"3862","GIC Glass Ionomer Occlusal Blocks"},
            {"3863","Bite Turbos"},
            {"3864","Debonding Single Arch"},
            {"3865","Debonding Two Arches"},
            {"3901","Apexification"},
            {"3902","Onlays: Indirect Composite/Porcelain"},
            {"3903","Onlays: 60% or more fine gold"},
            {"3904","Onlays: Precious Metal Alloy"},
            {"3905","Metal Acid Etch inlay"},
            {"3906","Removal of a Post in exceptional circumstances"},
            {"3907","Crown/Bridge restorations and other laboratory-based items (where there is no predetermined fee available under items 17(I) or 18(E))"},
            {"3908","Repair of a crown/bridge involving soldering (where there is no predetermined fee available under items 17(J) or 18(H))"},
            {"3909","Hemisection of a tooth"},
            {"3910","Precision attachments"},
            {"3911","Use of high impact acrylic in a denture"},
            {"391201","Incomplete treatment where there is no SDR fee"},
            {"3913","Balance fee for Continuation Case"},
            {"3914","Debonding Single Arch"},
            {"3915","Debonding Two Arches"},
            {"3992","Discretionary Fee for any other treatment not covered under occasional or extended occasional treatment"},
            {"3993","Ortho Discontinued"},
            {"3994","Balance fee for resumed treatments - where an incomplete fee has been claimed"},
            {"3995","Balance fee including laboratory costs for resumed treatments - where an incomplete fee has been claimed"},
            {"399601","Any other oral surgery procedures or complex procedures"},
            {"399701","Chairside factor: additional time necessarily spent with a patient"},
            {"399801","Fee for: Necessary treatment involving laboratory expenses not covered by the SDR"},
            {"399901","Fee for: Any other treatment"},
            {"4004","40[A][1]"},
            {"4005","40[A][2]"},
            {"4006","40[B]"},
            {"410101","Annual Fee for Childsmile 0 to 3 years (SIMD 1-3)"},
            {"410201","Annual Fee for Childsmile 0 to 3 years (SIMD 4-5)"},
            {"410301","Toothbrushing instruction for 0 to 3 years by Dentist"},
            {"410401","Toothbrushing instruction for 0 to 3 years by Dental Care Professional"},
            {"410501","Dietary Advice for 0 to 3 years by Dentist"},
            {"410601","Dietary Advice for 0 to 3 years by Dental Care Professional"},
            {"410701","Toothbrushing instruction for 3 to 5 years by Dentist"},
            {"410801","Toothbrushing instruction for 3 to 5 years by Dental Care Professional"},
            {"410901","Dietary Advice for 3 to 5 years by Dentist"},
            {"411001","Dietary Advice for 3 to 5 years by Dental Care Professional"},
            {"411101","Annual Fee for Childsmile 3 to 5 years (SIMD 1-3)"},
            {"420101","annual fee for preventative care 0 to 17 years (SIMD 1-2)"},
            {"420201","annual fee for preventative care 0 to 17 years (SIMD 3-5)"},
            {"4301","Resin filling, including acid etch retention in permanent molar and pre-molar teeth. Patient under 15 Years of Age - Per Tooth"},
            {"4302","Resin filling, including acid etch retention in permanent molar and pre-molar teeth. Patient under 15 Years of Age - Per Tooth where the Mo &/or DO surfaces are involved"},
            {"4401","Filling"},
            {"4402","Pre-Formed Metal Cap"},
            {"4403","Vital Pulpotomy/Root Treatment"},
            {"4404","Non Vital Pulpotomy/Root Treatment"},
            {"4405","Deciduous Filling Provided on Referral"},
            {"4406","Fissure Sealant (Preventative)"},
            {"440701","Topical Flouride"},
            {"4600","Referral"},
            {"470101","Occasional Examination/Assessment"},
            {"4801","Issue of a Prescription"},
            {"4901","Small Xray"},
            {"4911","Medium Xray"},
            {"4921","Large Film"},
            {"493001","OPT Analysis"},
            {"493101","Panoral Film"},
            {"4941","Colour Photographs: Clinical colour photographs and report"},
            {"5001","Dressings for Permanent or Retained Deciduous Teeth"},
            {"5002","Dressings for Deciduous Teeth"},
            {"5011","Incising an Abscess"},
            {"5021","Opening Root Canal(s) for Drainage of Permanent or Retained Deciduous Teeth"},
            {"5022","Opening Root Canal(s) for Drainage of Deciduous Teeth"},
            {"5031","One Canal Pulp Extirpation & Dressing to Seal Cavities"},
            {"5032","More Than One Canal Pulp Extirpation & Dressing to Seal Cavities"},
            {"5041","Grinding or Smoothing of Permanent or Retained Deciduous Teeth"},
            {"5042","Grinding or Smoothing of Deciduous Teeth"},
            {"5051","Sensitive Cementum or Dentine"},
            {"506101","Splinting in connection with external Trauma"},
            {"5062","Provision of Acid Etch Retained Composite Splints"},
            {"506301","Additional Fee for Metal Bar or Wire inserted in connection with 50(G)(2)"},
            {"5071","Reimplant Teeth Following Trauma"},
            {"5075","Removal of the Fractured Portion of a Natural Tooth Permanent or Retained Deciduous"},
            {"5076","Removal of the Fractured Portion of a Natural Tooth Deciduous"},
            {"5102","Temporary Crown Without Post"},
            {"5103","Temporary Crown Post Retained"},
            {"5104","Removal of a Crown Post Fractured at or Below Root Face"},
            {"5111","Refixing or Recementing an Inlay"},
            {"5112","Refixing or Recementing an Crown"},
            {"5121","Recementing Acid Etch Retained Bridge (Maryland)"},
            {"5122","Recementing or Refixing Bridge (Other Than a Maryland)"},
            {"513101","Removal of a bridge"},
            {"513201","Insertion of pin/screw/preformed post + recementing original bridge"},
            {"513301","Insertion of cast precious metal core + post & recementing original bridge"},
            {"513401","Insertion of non-precious metal core + post including Radix Anchor & Kurer Crown Saver + Rec. original bridge"},
            {"513501","Insertion of core + post prefabricated in non-precious metal + recementing original bridge"},
            {"5201","Extraction of Permanent Teeth"},
            {"5202","Extraction of Deciduous Teeth"},
            {"5206","Visit Fee for Extraction"},
            {"5211","Removal of Buried Root or Unerupted Tooth Involving Soft Tissue Only"},
            {"5212","Removal of Buried Root or Unerupted Tooth Involving Bone Removal for U&L 321/123"},
            {"5213","Removal of Buried Root or Unerupted Tooth Involving Bone Removal for U&L 87654/45678"},
            {"5214","Removal of Upper Impacted Third Molar Not Requiring Div. of Roots/Crowns"},
            {"5215","Removal of Upper Impacted Third Molar Requiring Div. of Roots/Crowns"},
            {"5216","Removal of Lower Impacted Third Molar Not Requiring Div. of Roots/Crowns"},
            {"5217","Removal of Lower Impacted Third Molar Requiring Div. of Roots/Crowns"},
            {"5301","Arrest of Haemorrhage Other Than 53[A][2]"},
            {"5302","Removal of Plugs and/or Sutures"},
            {"5311","Treatment of Infected Sockets"},
            {"5451","Sedation Visit Where the Number of Teeth Extracted is 1-4"},
            {"5452","Sedation Visit Where the Number of Teeth Extracted is 5-9"},
            {"5453","Sedation Visit Where the Number of Teeth Extracted is 10-16"},
            {"5454","Sedation Visit Where the Number of Teeth Extracted is 17+"},
            {"5455","Sedation Visit Where the Cost of trt. Carried out Under Sedation is up to & Including £10"},
            {"5456","Sedation Visit Where the Cost of trt. Carried out Under Sedation is Between £10.01 & £25"},
            {"5457","Sedation Visit Where the Cost of trt. Carried out Under Sedation is Between £25.01 & £50"},
            {"5458","Sedation Visit Where the Cost of trt. Carried out Under Sedation is Greater Than £50.00"},
            {"5460","Sedation Maximum per course of treatment."},
            {"5466","Additional Fee Where the Anaesthetist is Called to the Surgery <1.61km/1 mile"},
            {"5467","Additional Fee Where the Anaesthetist is Called to the Surgery >1.61km/1 mile"},
            {"5473","Visit Inhalation Provided, in Cases of Physical or Mental Handicap, or Anxiety"},
            {"5474","Visit Injection Provided, in Cases of Physical or Mental Handicap, or Anxiety"},
            {"5501","Repair - Crack/Fracture or Refixing or Providing & Fixing a Replacement Tooth Upper"},
            {"5502","Repair - Crack/Fracture or Refixing or Providing & Fixing a Replacement Tooth Lower"},
            {"5503","Repair - Fixing a Clasp or Providing & Fixing a Replacement Clasp Upper"},
            {"5504","Repair - Fixing a Clasp or Providing & Fixing a Replacement Clasp Lower"},
            {"550701","Maximum repair fee per Upper Denture"},
            {"550801","Maximum repair fee per Lower Denture"},
            {"551101","Refixing or replacement to metal dentures"},
            {"552101","Additional fee for Upper Impressions"},
            {"552201","Additional fee for Lower Impressions "},
            {"553101","Adjusting an Upper Denture"},
            {"553201","Adjusting a Lower Denture"},
            {"554105","Adjusting a Denture (other)"},
            {"555101","Relining or Rebasing UpperDentures"},
            {"555201","Relining or Rebasing Lower Dentures"},
            {"555301","Relining or Rebasing with addition of a Labial and/or Buccal Flange (Upper)"},
            {"555401","Relining or Rebasing with addition of a Labial and/or Buccal Flange (Lower)"},
            {"555501","Provision or Renewal of Soft Lining to an existing Upper Denture"},
            {"555601","Provision or Renewal of Soft Lining to an existing Lower Denture"},
            {"556001","1 Additional Clasp"},
            {"556002","1 Repair Balance Fee"},
            {"556004","1 Repair Balance Fee"},
            {"556005","1 Additional Gum"},
            {"556006","1 Repair Balance Fee"},
            {"556007","1 Additional Clasp"},
            {"556008","2 or more repairs Balance Fee"},
            {"556010","2 or more repairs Balance Fee"},
            {"556011","1 Additional Gum"},
            {"556012","2 or more repairs Balance Fee"},
            {"556013","1 Additional Clasp"},
            {"556014","Refix Clasp Balance Fee"},
            {"556016","Refix Clasp Balance Fee"},
            {"556017","1 Additional Gum"},
            {"556018","Refix Clasp Balance Fee"},
            {"556019","Any 2 additions with or without repairs"},
            {"5561","Addition of an Upper Clasp including any associated gum"},
            {"5562","Addition of a Lower Clasp including any associated gum"},
            {"5563","Addition of an Upper Tooth including any associated gum"},
            {"5564","Addition of a Lower Tooth including any associated gum"},
            {"556501","Addition of a new Upper Gum not in addition under 55(D)(1) or (2)"},
            {"556601","Addition of a new Lower Gum not in addition under 55(D)(1) or (2)"},
            {"556701","1 Additional Tooth"},
            {"556801","1 Additional Tooth"},
            {"556901","1 Additional Tooth"},
            {"557110","Stainless steel or chrome cobalt (Soldering or Welding Additions)"},
            {"558101","Upper Repair - Cracks or fractures in the acrylic of a removable appliance"},
            {"5582","Upper Repair - Metal comp. or providing & fixing a metal comp. on a removable appliance"},
            {"558301","Repair of a Functional appliance"},
            {"558401","Upper Repair of a Fixed App. involving the replace. of 2 or more bracket bands/archwires"},
            {"558501","Additional fee for an Upper Impression"},
            {"558601","Additional fee for an Lower Impression"},
            {"558701","Lower Repair - Cracks or fractures in the acrylic of a removable appliance"},
            {"5588","Lower Repair - Metal comp. or providing & fixing a metal comp. on a removable appliance"},
            {"558901","Lower Repair of a Fixed App. involving the replace. of 2 or more bracket bands/archwires"},
            {"559101","Recement one band (Other repairs or adjustments to a Fixed or Removable appliance)"},
            {"559102","Each additional band (Other repairs or adjustments to a Fixed or Removable appliance)"},
            {"559103","Removal of a Bonded Retainer (Other repairs or adjustments to a Fixed or Removable appliance)"},
            {"559104","Removal of Ligatures  (Other repairs or adjustments to a Fixed or Removable appliance)"},
            {"559105","Removal of a band or spring"},
            {"559106","Removal of a whole fixed appliance"},
            {"559107","Removal of both arches (Maximum Fee)"},
            {"559108","Adjustment of Fixed/Removable appliance"},
            {"559109","Relining/Rebasing an appliance"},
            {"559110","1 Bond (Recementing Bonded Retainers)"},
            {"559111","2 or more Bonds (Recementing Bonded Retainers)"},
            {"559112","1 Visit (Enamel Stripping/Discing)"},
            {"559113","2 Visits (Enamel Stripping/Discing)"},
            {"559114","Maximum (Enamel Stripping/Discing)"},
            {"559501","Upper Maximum Repair Fee"},
            {"559601","Lower Maximum Repair Fee"},
            {"5601","Treatment of Acute Conditions"},
            {"5701","Domiciliary Visit < 16.1km/10 miles"},
            {"5702","Domiciliary Visit 16.1km/10 miles to 64.4km/40 miles"},
            {"5703","Domiciliary Visit > 64.4km/40 miles"},
            {"5711","Recalled Attendance < 1.61km/1 mile"},
            {"5712","Recalled Attendance > 1.61km/1 mile"},
            {"5811","Amalgam Filling in a Single Surface"},
            {"5812","Two or More Amalgam Fillings in the Same Tooth"},
            {"5813","Two or More Amalgam Fillings in the Same Tooth MO or DO"},
            {"5814","Three or More Amalgam Fillings in the Same Tooth MOD"},
            {"5820","Composite Resin Filling Two or More in the Same Tooth"},
            {"5821","Composite Resin Filling"},
            {"5822","Acid Etch 1 Incisal Angle MI"},
            {"5823","Acid Etch 1 Incisal Edge I"},
            {"5824","Acid Etch 2 Incisal Angles MID"},
            {"5825","Additional Fee for Buccal Cusp"},
            {"5826","GI Filling 3m(g)"},
            {"5827","GI Filling in Two Surfaces 3d(g)3m(g)"},
            {"5831","Pin or Screw Retention"},
            {"5836","Treatment of Permanent Tooth Using GI, Single Filling 1m or 1mi"},
            {"5837","Treatment of Permanent Tooth Using GI, Double Filling 1m or 1mi"},
            {"5838","Maximum Fee for Combination of Fillings Without Pins, Acid Etch or Buccal Cusp"},
            {"5839","Maximum Fee for Combination of Fillings With Pins, Acid Etch or Buccal Cusp"},
            {"5841","Incisor or Canine, Root Filling of Each Root Canal"},
            {"5842","Upper Premolar, Root Filling of Each Root Canal"},
            {"5843","Lower Premolar, Root Filling of Each Root Canal"},
            {"5851","Replacement Bridge (Fab. in Lab in cases Where Bridge is to be Retained for at Least 3 Months)"},
            {"5852","Replacement Bridge (Any Bridge Other Than 58[G][1])"},
            {"590001","F/F Replacement Acrylic Denture"},
            {"590101","F/- Replacement Acrylic Denture"},
            {"590201","-/F Replacement Acrylic Denture"},
            {"5903","P/- Replacement Acrylic Denture"},
            {"590401","Additional fee for Stainless Steel Lingual or Palatal Bar"},
            {"5905","-/P Replacement Acrylic Denture"},
            {"591001","Maximum Fee (Combination of Upper & Lower Acrylic Dentures)"},
            {"591101","F/- Dentures in Chrome Cobalt or Stainless Steel"},
            {"591201","-/F Dentures in Chrome Cobalt or Stainless Steel"},
            {"5916","Additional Fee for Backings"},
            {"593101","Provision of Soft Lining where the denture is being provided at the same time"},
            {"593201","Provision of Soft Lining where the denture is being provided at the same time"},
            {"594101","Laboratory constructed Special Trays"},
            {"594201","Laboratory constructed Special Trays"},
            {"595101","Inclusion of a permanent Patient Identification Marker"},
            {"595201","Inclusion of a permanent Patient Identification Marker"},
            {"6001","Filling Deciduous Teeth Treatment"},
            {"6002","Pre-Formed Metal Cap Deciduous Treatment"},
            {"6003","Vital Pulpotomy/Root Trt. Deciduous Treatment"},
            {"6004","Non-Vital Pulpotomy/Root Trt. Deciduous Treatment"},
            {"620001","F/F (25% of scale fee, Impression taken & bite registered)"},
            {"620101","F/- (25% of scale fee, Impression taken & bite registered)"},
            {"6202"," P/- (25% of scale fee, Impression taken & bite registered)"},
            {"620301","-/F (25% of scale fee, Impression taken & bite registered)"},
            {"6204","-/P 25% of scale fee, Impression taken & bite registered)"},
            {"620501","Maximum combinations"},
            {"621001","F/F (50% of scale fee, Set-up to Try-in Stage)"},
            {"621101","F/- (50% of scale fee, Set-up to Try-in Stage)"},
            {"6212","P/- 50% of scale fee, Set-up to Try-in Stage"},
            {"621301","-/F (50% of scale fee, Set-up to Try-in Stage)"},
            {"6214","-/P (50% of scale fee, Set-up to Try-in Stage)"},
            {"621501","Maximum combinations"},
            {"622001","F/F (66 2/3% of scale fee)"},
            {"622101","F/- (66 2/3% of scale fee)"},
            {"6222","P/- (66 2/3% of scale fee)"},
            {"622301","-/F (66 2/3% of scale fee)"},
            {"6224","-/P (66 2/3% of scale fee)"},
            {"622501","Maximum combinations"},
            {"623001","F/F (95% of scale fee, Completed but not fitted)"},
            {"623101","F/- (95% of scale fee, Completed but not fitted)"},
            {"6232","P/-, (95% of scale fee, Completed but not fitted)"},
            {"623301","-/F (95% of scale fee, Completed but not fitted)"},
            {"6234","-/P, (95% of scale fee, Completed but not fitted)"},
            {"623501","Maximum combinations"},
            {"624001","F/F Metal (25% of scale fee, Impression taken & bite registered)"},
            {"624101","F/- Metal (25% of scale fee, Impression taken & bite registered)"},
            {"6242","P/- Metal (25% of scale fee, Impression taken & bite registered)"},
            {"624301","-/F Metal (25% of scale fee, Impression taken & bite registered)"},
            {"6244","-/P Metal (25% of scale fee, Impression taken & bite registered)"},
            {"624501","Maximum combinations"},
            {"625001","F/F Metal (50% of scale fee, Set-up to Try-in Stage)"},
            {"625101","F/- Metal (50% of scale fee, Set-up to Try-in Stage)"},
            {"6252","P/- Metal (50% of scale fee, Set-up to Try-in Stage)"},
            {"625301","-/F Metal (50% of scale fee, Set-up to Try-in Stage)"},
            {"6254","-/P Metal (50% of scale fee, Set-up to Try-in Stage)"},
            {"625501","Maximum combinations"},
            {"626101","F/- Metal (70% of scale fee, Set-up to Try-in Stage)"},
            {"626201","-/F Metal (70% of scale fee, Set-up to Try-in Stage)"},
            {"6263","P/- Metal Plate Design (70% of scale fee, Set-up to Try-in Stage)"},
            {"6264","Skeleton design (P/- metal denture with Single Connecting Bars, 70% of fee scale)"},
            {"6265","Skeleton design (P/- metal denture with Multiple Connecting Bars, 70 % of fee scale)"},
            {"6266","-/P Metal Plate Design (70% of scale fee, Set-up to Try-in Stage)"},
            {"6267","Skeleton design (-/P metal denture with Single Connecting Bars, 70% of fee scale)"},
            {"6268","Skeleton design (-/P metal denture with Multiple Connecting Bars, 70 % of fee scale)"},
            {"627101","F/- Metal (85% of scale fee, Tried in the Wax State)"},
            {"627201","-/F Metal (85% of scale fe, Tried in the Wax State)"},
            {"6273","P/- Metal Plate Design (85% of scale fee, Tried in the Wax State)"},
            {"6274","Skeleton design (P/- metal denture with Single Connecting Bars, 85% of fee scale)"},
            {"6275","Skeleton design (P/- metal denture with Multiple Connecting Bars, 85% of fee scale)"},
            {"6276","-/P Metal Plate Design (85% of scale fee, Tried in the Wax State)"},
            {"6277","Skeleton design (-/P metal denture with Single Connecting Bars, 85% of fee scale)"},
            {"6278","Skeleton design (-/P metal denture with Multiple Connecting Bars, 85% of fee scale)"},
            {"628101","F/- Metal (95% of scale fee, Completed but Not Fitted)"},
            {"628201","-/F Metal (95% of scale fee, Completed but Not Fitted)"},
            {"6283","P/- Metal Plate Design (95% of scale fee, Completed but Not Fitted)"},
            {"6284","Skeleton design (P/- metal denture with Single Connecting Bars, 95% of fee scale)"},
            {"6285","Skeleton design (P/- metal denture with Multiple Connecting Bars, 95% of fee scale)"},
            {"6286","-/P Metal Plate Design (95% of scale fee, Completed but Not Fitted)"},
            {"6287","Skeleton design (-/P metal denture with Single Connecting Bars, 95% of fee scale)"},
            {"6288","Skeleton design (-/P metal denture with Multiple Connecting Bars, 95% of fee scale)"},
            {"6301","Dressing"},
            {"6311","Incising an Abscess"},
            {"6321","Opening Root Canal"},
            {"6331","One Canal, Pulp Extirpation & Dressing to Seal Cavities in Perm. Teeth"},
            {"6332","More Than One Canal, Pulp Extirpation & Dressing to Seal Cavities in Perm. Teeth"},
            {"6341","Incisor Tooth (1 Visit, Any Other Endodontic Trt. Including Combinations of 63[B][C]+[D])"},
            {"6342","Upper Premolar Tooth (1 Visit, Any Other Endodontic Trt. Including Combinations of 63[B][C]+[D])"},
            {"6343","Lower Premolar Tooth (1 Visit, Any Other Endodontic Trt. Including Combinations of 63[B][C]+[D])"},
            {"6344","Molar Tooth (1 Visit, Any Other Endodontic Trt. Including Combinations of 63[B][C]+[D])"},
            {"6351","Incisor Tooth (More Than 1 Visit, Any Other Endodontic Trt. Including Combinations of 63[B][C]+[D])"},
            {"6352","Upper Premolar Tooth (More Than 1 Visit, Any Other Endodontic Trt. Including Combinations of 63[B][C]+[D])"},
            {"6353","Lower Premolar Tooth (More Than 1 Visit, Any Other Endodontic Trt. Including Combinations of 63[B][C]+[D])"},
            {"6354","Molar Tooth (More Than 1 Visit, Any Other Endodontic Trt. Including Combinations of 63[B][C]+[D])"},
            {"640001","Additional fee for first or only Veneer provided"},
            {"6401","Incomplete Porcelain Veneers, Not Fitted"},
            {"6500","Additional Fee (1st or only Crown in the same jaw)"},
            {"6501","Incomplete Porcelain Jacket Crown"},
            {"6511","Full or Jacket Crown Cast in Fine Gold or Precious Metal With Bonded Porcelain"},
            {"6512","Full or Jacket Crown Cast in Non-Precious Metal With Bonded Porcelain"},
            {"6513","Porcelain Jacket Crown Thermally Bonded to Wrought Platinum Coping"},
            {"6522","Cast Full or Jacket Crown in Precious Metal Alloy"},
            {"6523","1 Tooth (Cast Full or Jacket Crown in Non-Precious Metal Alloy)"},
            {"7001","No of Visits for Care and Treatment"},
            {"7003","No of Domiciliary Visits"},
            {"700501","Recall"},
            {"700502","Inspection/examination"},
            {"700503","School"},
            {"700504","Self"},
            {"700505","GDP"},
            {"700506","GMP"},
            {"700508","Hospital"},
            {"700509","Social Services"},
            {"700510","Other"},
            {"700511","HV/Nurse"},
            {"700601","Mental Health"},
            {"700602","Learning Disability"},
            {"700603","Physical Disability"},
            {"700604","Child Health - Pre School"},
            {"700605","Child Health - School Child"},
            {"700606","Maternity and Neonatal"},
            {"700607","Psychogeriatric"},
            {"700608","Geriatric"},
            {"700610","Medically Compromised"},
            {"700611","Anxiety / Phobia"},
            {"700612","Acute In-patient"},
            {"700613","Prison"},
            {"700614","Other"},
            {"700615","Access Patient"},
            {"700616","Undergraduate Outreach"},
            {"700617","Medical consultant-led treatment plan"},
            {"700618","Child Health - Looked After (all)"},
            {"700712","Emergency"},
            {"700713","Emergency & Routine"},
            {"700714","Routine"},
            {"700715","Orthodontic"},
            {"700716","Oral Medicine"},
            {"700717","Oral Surgery"},
            {"701201","Patient Assessment"},
            {"7013","Acclimatisation"},
            {"7014","Hypnosis"},
            {"7015","Oral/Transmucosal Sedation"},
            {"7016","Consultant-led Day-case Sedation"},
            {"701701","General Anaesthesia"},
            {"702101","Special care need modified casemix tool (mCMT) total score 0"},
            {"702102","Special care need modified casemix tool (mCMT) total score 1"},
            {"702103","Special care need modified casemix tool (mCMT) total score 2"},
            {"702104","Special care need modified casemix tool (mCMT) total score 3"},
            {"702105","Special care need modified casemix tool (mCMT) total score 4"},
            {"702106","Special care need modified casemix tool (mCMT) total score 5"},
            {"702107","Special care need modified casemix tool (mCMT) total score 6"},
            {"702108","Special care need modified casemix tool (mCMT) total score 7"},
            {"702109","Special care need modified casemix tool (mCMT) total score 8"},
            {"702110","Special care need modified casemix tool (mCMT) total score 9"},
            {"702111","Special care need modified casemix tool (mCMT) total score 10"},
            {"703101","Incomplete Treatment - Limited patient compliance"},
            {"730101","Partial scaling 18 years or over at beginning of course of treatment"},
            {"730199","Any other Incomplete Treatment"},
            {"8001","Initial Telephone Call Triaging"},
            {"8011","Advice and Closing the Case"},
            {"8021","Advice and a Prescription - Antibiotics and or Analgesics Closing the Case"},
            {"8031","Appointment for Treatment Arranged (Further Covid Triaging to Determine Status) Red Covid Pathway"},
            {"8041","Appointment for Treatment Arranged (Further Covid Triaging to Determine Status) Green Covid Positive"},
            {"8051","Appointment Visit (Treatment) Aerosol Generating Procedure"},
            {"8061","Non Aerosol Procedure"},
            {"8071","Unable to Deliver Case - Phobia/Co-operation/Consent Issue"},
            {"8081","Aerosol Generated Procedure"},
            {"8082","Interpreter Required"},
            {"8083","Multiple Contact with UDCC Required"},
            {"8084","Any Referral not included in 80[D] or [E]"},
            {"8085","Where the Visors being used for the patient require to be disposed of due to splatter contamination"},
            {"9001","reapproval for change to treatment plan not resulting in a change to the total of fees on the originally approved claim"},
            {"REGN","Registration"}
        };
    }
}
