using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Treatment_Mapper.Mapping_Functions
{
    public class CodeValidation

        
    {
       
        public readonly Dictionary<string,int> valid_codes = new Dictionary<string, int>()
        {
            {"Exam",100},
            {"Exam & Scale & Polish ",101},
            {"New Patient Exam",102},
            {"Review",103},
            {"Assessment & Advice",104},
            {"Small Radiograph",105},
            {"Intraoral Photographs",106},
            {"Panoral Radiograph",107},
            {"Cephalometric Radiographic Image",108},
            {"Clinical Photographs",109},
            {"Periapical X Ray",110},
            {"Acute Mucosal Infection",111},
            {"Analysis Of Saliva Sample",112},
            {"Band 1 Referral for Advanced Mandatory Treatment",113},
            {"Band 2 Referral for Advanced Mandatory Treatment",114},
            {"Band 3 Referral for Advanced Mandatory Treatment",115},
            {"Diagnostic Wax Up",116},
            {"Dry Socket",117},
            {"Study Models",118},
            {"Treatment of Infected Sockets",119},
            {"Incising an Abscess",120},
            {"Scale & Polish",200},
            {"Periodontal Scaling And Root Planing",201},
            {"Hygiene 20",202},
            {"Hygiene 30",203},
            {"Hygiene 45",204},
            {"Hygiene 60",205},
            {"Full Mouth Debridement",206},
            {"Tooth Dressing",207},
            {"Crown Lengthening",208},
            {"Airflow",209},
            {"Bone Grafting",210},
            {"Guided Tissue Regeneration",211},
            {"Subepithelial Connective Tissue Graft",212},
            {"Splints",213},
            {"Periodontal Maintenance ",214},
            {"Hygiene Treatment",215},
            {"Perio-Chip",216},
            {"Topical Application Of Fluoride Varnish",300},
            {"Fissure Sealant - Per Tooth",301},
            {"Amalgam Filling",400},
            {"Composite Filling",401},
            {"Temporary Filling",402},
            {"Glass Ionomer",403},
            {"Fissure Sealant - Composite",404},
            {"Fissure Sealant - Glass Ionomer",405},
            {"Fissure Sealant - Composite & Glass Ionomer",406},
            {"Inlay Imps & Prep",407},
            {"Inlay/Onlay - Gold",408},
            {"Inlay/Onlay - Porcelain/Ceramic",409},
            {"Inlay/Onlay",410},
            {"Recement Inlay/Onlay",411},
            {"Veneer Imps",412},
            {"Porcelain Veneer",413},
            {"Crown Imps & Prep",414},
            {"Crown ",415},
            {"Porcelain Crown",416},
            {"Porcelain Bonded Crown",417},
            {"Bonded Crown",418},
            {"Gold Crown",419},
            {"Metal Crown",420},
            {"Temporary Crown",421},
            {"Recement Crown",422},
            {"Post & Core",423},
            {"Recement Post",424},
            {"Core Buildup, Including Any Pins",425},
            {"Pin Retention",426},
            {"Post Removal ",427},
            {"Coping",428},
            {"Emax Crown",429},
            {"Zirconium Crown",430},
            {"Veneer",431},
            {"Crown Repair",432},
            {"RCT - Molar",500},
            {"RCT - Premolar Tooth",501},
            {"RCT - Incisor",502},
            {"RCT additional visit",503},
            {"Re-RCT",504},
            {"Pulpal Therapy ",505},
            {"Pulpotomy (Excluding Final Restoration) ",506},
            {"Extraction",600},
            {"Surgical/Wisdom Tooth Extraction",601},
            {"Suture Removal",602},
            {"Removal Of Impacted Tooth - Soft Tissue",603},
            {"Removal Of Impacted Tooth - Partially Bony",604},
            {"Coronectomy - Intentional Partial Tooth Removal",605},
            {"Biopsy Of Oral Tissue - Hard (Bone, Tooth)",606},
            {"Apicectomy/Periradicular Surgery",607},
            {"Primary Denture Impressions",700},
            {"Secondary Denture Impressions",701},
            {"Denture Bite",702},
            {"Denture Try-in",703},
            {"Full Upper Acrylic Denture",704},
            {"Full Lower Acrylic Denture",705},
            {"Full Upper & Lower Acrylic Denture",706},
            {"Partial Acrylic Denture",707},
            {"Full Upper Chrome Denture",708},
            {"Full Lower Chrome Denture",709},
            {"Full Upper & Lower Chrome Denture Fit",710},
            {"Partial Chrome Denture",711},
            {"Tooth Addition to a Acrylic Denture",712},
            {"Tooth Addition to a Chrome Denture",713},
            {"Adjust Denture ",714},
            {"Denture Repair",715},
            {"Denture Reline",716},
            {"Soft Lining",717},
            {"Soft Lining - New Denture",718},
            {"Tissue Conditioning",719},
            {"Denture Ease",720},
            {"Denture",721},
            {"Implant Consultation",800},
            {"Placement Of Implant",801},
            {"Interim Abutment",802},
            {"Implant Retained Denture",803},
            {"Connecting Bar for Implant",804},
            {"Implant Abutment",805},
            {"Implant Crown",806},
            {"Implant -  Full Denture",807},
            {"Implant - Partial Denture",808},
            {"Implant - Bridge",809},
            {"Repair Implant Supported Prosthesis",810},
            {"Debridement Of A Periimplant Defect",811},
            {"Bone Graft At Time Of Implant Placement",812},
            {"Implant Review",813},
            {"Implant Maintenance Procedures",814},
            {"Bridge Prep",900},
            {"Bridge Try In",901},
            {"Bonded Bridge Pontic",902},
            {"Bonded Bridge Retainer",903},
            {"Gold Bridge Pontic",904},
            {"Gold Bridge Retainer",905},
            {"Porcelain Bridge Pontic",906},
            {"Porcelain Bridge Retainer",907},
            {"Porcelain Bonded Bridge Pontic",908},
            {"Porcelain Bonded Bridge Retainer",909},
            {"Maryland Bridge",910},
            {"Maryland Wing",911},
            {"Clasp",912},
            {"Recement Bridge",913},
            {"Stress Breaker",914},
            {"Precision Attachment",915},
            {"Bridge Repair",916},
            {"Bridge Retainer",917},
            {"Bridge Pontic",918},
            {"Temporary Bridge Unit",919},
            {"Bridge",920},
            {"Ortho Assessment/Review/Exam",1000},
            {"Ortho Review",1001},
            {"Ortho Study Models",1002},
            {"Ortho Retention",1004},
            {"Invisalign",1005},
            {"Removable Upper Appliance",1006},
            {"Removable Lower Appliance",1007},
            {"Functional Appliance Fit",1008},
            {"Fixed Upper Appliance",1009},
            {"Fixed Lower Appliance",1010},
            {"Retainer Upper",1011},
            {"Retainer Lower",1012},
            {"Ortho Extraction",1013},
            {"Ortho New Patient Exam",1014},
            {"Ortho Debond",1015},
            {"Orthodontic Separators",1016},
            {"Orthodontic Impressions",1017},
            {"Ortho Adjustment",1018},
            {"Ortho Bond up",1019},
            {"Ortho Retainer Fit",1020},
            {"Ortho Supervision of Retention",1021},
            {"Orthodontic Emergency",1022},
            {"Ortho Replacement Removeable Appliance",1023},
            {"Ortho Replacement Essix Retainer",1024},
            {"Ortho Replacement Fixed Retainer",1025},
            {"Ortho Ceramic Brackets Fixed Appliance Upper",1026},
            {"Ortho Ceramic Brackets Fixed Appliance Lower",1027},
            {"Ortho Sectional Steel Appliance",1028},
            {"Ortho Sectional Ceramic Appliance",1029},
            {"Ortho  Bonded (Fixed) Retainer",1030},
            {"Ortho Stage Payment",1031},
            {"Ortho - Other Orthodontic Treatment",1032},
            {"Oral/Facial Photographic Images",1033},
            {"Ortho Photographs",1034},
            {"Ortho Removable Appliance",1035},
            {"Functional Appliance Review",1040},
            {"Repair To An Appliance Fitted By Another Dentist",1041},
            {"Office Visit - After Regularly Scheduled Hours",1100},
            {"Case Presentation, Detailed And Extensive Treatment Planning",1101},
            {"Antibiotic Prescription",1102},
            {"Prescription",1103},
            {"Sensitive Dentine",1104},
            {"Lucia Jig",1105},
            {"Bite Guard",1106},
            {"Mouth Guard",1107},
            {"Sports Mouthguard",1108},
            {"Repair And/Or Reline Of Occlusal Guard",1109},
            {"Occlusion Analysis - Mounted Case",1110},
            {"Occlusal Adjustment",1111},
            {"Enamel Microabrasion  ",1112},
            {"In Surgery Bleaching (Whitening)",1113},
            {"Home Bleaching Kit (Whitening)",1114},
            {"Bleaching Trays",1115},
            {"Stone/Smooth Tooth",1116},
            {"Impressions",1117},
            {"Payment Refund",1118},
            {"Discount",9975},
            {"Caries",9976},
            {"Root Filled",9977},
            {"Reset Tooth",9978},
            {"Tooth Needs to be Extracted",9979},
            {"Missing Tooth",9980},
            {"Drifted Right",9981},
            {"Drifted Left",9982},
            {"Closed Gap",9983},
            {"Fractured Tooth",9984},
            {"Watch Tooth",9985},
            {"Other Tooth Specific Treatment",9986},
            {"Opening Balance",9987},
            {"Deposit for Future Work",9988},
            {"Decay",9989},
            {"General Note",9990},
            {"Partially Erupted Tooth",9991},
            {"Retained Root",9992},
            {"Unerupted or exfoliated teeth",9993},
            {"Arrested Caries",9994},
            {"Tooth Specific Note",9995},
            {"Early Caries",9996},
            {"Cavity",9997},
            {"Surface Wear (Worn)",9998},
            {"Other Treatment",9999}

        };
        public Dictionary<string, int> Codes { get { return valid_codes; }  }
        public  List<int> ValidateCode()
        {
            List<int> validated_codes = new List<int>();

            foreach (KeyValuePair<string, int> T in valid_codes)
            {
                validated_codes.Add(T.Value);
            }
            return validated_codes;
        }
    }
}
